services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Password1"
    ports:
      - "1435:1433"

  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=proekt_db;User Id=sa;Password=YourStrong!Password1;TrustServerCertificate=True;"
