# render.yaml

databases:
  - name: medreports-db
    databaseName: proektdb
    plan: free
    region: frankfurt
    postgresMajorVersion: "16"

services:
  - type: web
    name: medreports
    runtime: docker
    plan: free
    region: frankfurt

    dockerfilePath: ./Dockerfile
    dockerContext: .

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: medreports-db
          property: internalConnectionString

    autoDeploy: true